name: CI

on:
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install lcov
          sudo apt install pkg-config

      - name: Build and Test
        run: |
          bazel test //... --color=yes --config=buildbuddy > >(tee -a /tmp/test.log) 2>&1

  converage:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install lcov
          sudo apt install pkg-config

      - name: Read secrets
        run: |
          CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"

      - name: Compute and publish Coverage Report
        run: |
          bazel coverage --instrumentation_filter="[:]" --instrument_test_targets=true --combined_report=lcov --sandbox_base=/run/shm //...
          genhtml bazel-out/_coverage/_coverage_report.dat --output-directory coverage

          lcov --list bazel-out/_coverage/_coverage_report.dat
          bash <(curl -s https://codecov.io/bash) -f bazel-out/_coverage/_coverage_report.dat || echo "Codecov did not collect coverage reports"
